/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cavenator.ui;

import cavenator.domain.CaveGenerator;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

public class GUI extends javax.swing.JFrame {

    private CaveGenerator cavegen;

    /**
     * Creates new form GUI
     */
    public GUI(CaveGenerator cavegen) {
        initComponents();
        this.setLocation(200, 100);
        this.cavegen = cavegen;
    }

    /**
     * Paint CavePanel based on map returned by cavegenerator. Each map tile is
     * 2x2 px on screen.
     *
     * @param map
     */
    public void setCaveContent(String[][] map) {
        Graphics g = cavePanel1.getGraphics();
        for (int y = 0; y < map.length; y++) {
            for (int x = 0; x < map[y].length; x++) {
                if (map[y][x] == "#") {
                    g.setColor(Color.BLACK);
                    g.fillRect(2 * x, 2 * y, 2, 2);
                } else {
                    g.setColor(Color.WHITE);
                    g.fillRect(2 * x, 2 * y, 2, 2);
                }
            }
        }
        cavePanel1.paintComponents(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cavePanel1 = new javax.swing.JPanel();
        buttonBackground = new javax.swing.JPanel();
        generateButton = new javax.swing.JButton();
        shapeButton = new javax.swing.JButton();
        detailButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cavePanel1.setBackground(new java.awt.Color(60, 63, 95));
        cavePanel1.setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout cavePanel1Layout = new javax.swing.GroupLayout(cavePanel1);
        cavePanel1.setLayout(cavePanel1Layout);
        cavePanel1Layout.setHorizontalGroup(
            cavePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        cavePanel1Layout.setVerticalGroup(
            cavePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        buttonBackground.setBackground(new java.awt.Color(153, 153, 153));

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        shapeButton.setText("Shape");
        shapeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shapeButtonActionPerformed(evt);
            }
        });

        detailButton.setText("Detail");
        detailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Try shaping and detailing in different order");

        javax.swing.GroupLayout buttonBackgroundLayout = new javax.swing.GroupLayout(buttonBackground);
        buttonBackground.setLayout(buttonBackgroundLayout);
        buttonBackgroundLayout.setHorizontalGroup(
            buttonBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonBackgroundLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(generateButton)
                .addGap(18, 18, 18)
                .addComponent(shapeButton)
                .addGap(18, 18, 18)
                .addComponent(detailButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonBackgroundLayout.setVerticalGroup(
            buttonBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonBackgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(buttonBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shapeButton)
                    .addComponent(generateButton)
                    .addComponent(detailButton)
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cavePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cavePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        cavegen.generateCaves(45);
        setCaveContent(cavegen.getMap());
    }//GEN-LAST:event_generateButtonActionPerformed

    private void shapeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shapeButtonActionPerformed
        try {
            cavegen.shapeMap(2, 12);
            setCaveContent(cavegen.getMap());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "First generate a map", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_shapeButtonActionPerformed

    private void detailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailButtonActionPerformed
        try {
            cavegen.shapeMap(1, 4);
            setCaveContent(cavegen.getMap());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "First generate a map", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_detailButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonBackground;
    private javax.swing.JPanel cavePanel1;
    private javax.swing.JButton detailButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton shapeButton;
    // End of variables declaration//GEN-END:variables

}
